[package]
name = "ssb-legacy-msg-js"
version = "1.0.0"
authors = ["Piet Geursen <pietgeursen@gmail.com>"]
license = "LGPL-3.0"

[lib]
name = "ssb_legacy_msg_js"
crate-type = ["staticlib"]

[dependencies]
error-chain = "0.12.0"
ssb-legacy-msg-data = { git = "https://github.com/ssbrs/legacy-msg-data" }
serde = "1.0.80"
serde_cbor = "0.10.2"
serde_derive = "1.0.80"
base64 = "0.9.3"
indexmap = "1.0.1"
ryu-ecmascript = "0.1.1"
# strtod = "0.0.2"
strtod = { git = "https://github.com/ssbrs/strtod" }
encode_unicode = "0.3.3"

[dependencies.serde_json] 
version = "1.0.32"
features = ["preserve_order"]
